#!/bin/sh

# These values should be automatically updated by the
# build process of hub-packman.

PACKMAN_LATEST_RELEASE=hub-packman-0.0.1.jar
PACKMAN_LATEST_SNAPSHOT=hub-packman-0.0.2-SNAPSHOT.jar

# If you would like to enable the shell script to use
# the latest snapshot instead of the latest release,
# specify PACKMAN_USE_SNAPSHOT=1 in your environment.
# The default is to NOT use snapshots. If you enable
# snapshots, the jar file will always be downloaded.

PACKMAN_USE_SNAPSHOT=${PACKMAN_USE_SNAPSHOT:-0}

# To override the default location of /tmp, specify
# your own PACKMAN_JAR_PATH in your environment and
# *that* location will be used.

PACKMAN_JAR_PATH=${PACKMAN_JAR_PATH:-/tmp}

all_command_line_args=$@

run() {
  get_packman
  run_packman
}

get_packman() {
  VERSION_FILE_DESTINATION="${PACKMAN_JAR_PATH}/version.txt"
  CURRENT_VERSION=""
  if [ -f $VERSION_FILE_DESTINATION ]; then
    CURRENT_VERSION=$( <$VERSION_FILE_DESTINATION )
  fi

  curl -o $VERSION_FILE_DESTINATION https://blackducksoftware.github.io/hub-packman/version.txt
  LATEST_VERSION=$( <$VERSION_FILE_DESTINATION )

  if [ "$CURRENT_VERSION" = "$LATEST_VERSION" ]; then
    echo "You have the latest version, the local file will be used."
    USE_LOCAL=1
  else
    echo "You do not have the latest version, so a new file will be downloaded."
    USE_LOCAL=0
  fi

  if [ $PACKMAN_USE_SNAPSHOT -eq 1 ]; then
    echo "will look for snapshot: ${PACKMAN_LATEST_SNAPSHOT}"
    PACKMAN_DESTINATION="${PACKMAN_JAR_PATH}/${PACKMAN_LATEST_SNAPSHOT}"
    PACKMAN_SOURCE=$PACKMAN_LATEST_SNAPSHOT
  else
    echo "will look for release: ${PACKMAN_LATEST_RELEASE}"
    PACKMAN_DESTINATION="${PACKMAN_JAR_PATH}/${PACKMAN_LATEST_RELEASE}"
    PACKMAN_SOURCE=$PACKMAN_LATEST_RELEASE
  fi

  if [ $USE_LOCAL -eq 1 ] && [ -f $PACKMAN_DESTINATION ]; then
    echo "using local ${PACKMAN_DESTINATION}"
  else
    echo "getting ${PACKMAN_SOURCE} from remote"
    curl -o $PACKMAN_DESTINATION https://blackducksoftware.github.io/hub-packman/$PACKMAN_SOURCE
    echo "saved ${PACKMAN_SOURCE} to ${PACKMAN_DESTINATION}"
  fi
}

run_packman() {
  echo "running packman: ${PACKMAN_DESTINATION} ${all_command_line_args}"
  java -jar $PACKMAN_DESTINATION $all_command_line_args
}

run
