#!/bin/bash

# This value should not be updated - the Jenkins
# build process will, for ANY snapshot build,
# override the latest snapshot jar.

DETECT_LATEST_SNAPSHOT=hub-detect-latest-SNAPSHOT.jar

# This value should be automatically updated by the
# gradle build process for a non-snapshot build.
DETECT_LATEST_RELEASE_VERSION="0.0.7"
DETECT_LATEST_RELEASE="hub-detect-${DETECT_LATEST_RELEASE_VERSION}.jar"

# If you would like to enable the shell script to use
# the latest snapshot instead of the latest release,
# specify DETECT_USE_SNAPSHOT=1 in your environment.
# The default is to NOT use snapshots. If you enable
# snapshots, the jar file will always be downloaded.

DETECT_USE_SNAPSHOT=${DETECT_USE_SNAPSHOT:-0}

# To override the default location of /tmp, specify
# your own DETECT_JAR_PATH in your environment and
# *that* location will be used.

DETECT_JAR_PATH=${DETECT_JAR_PATH:-/tmp}

JAVAOPTS="$@"

run() {
  get_detect
  run_detect
}

get_detect() {
  VERSION_FILE_DESTINATION="${DETECT_JAR_PATH}/hub-detect-latest-commit-id.txt"
  CURRENT_VERSION=""
  if [ -f $VERSION_FILE_DESTINATION ]; then
    CURRENT_VERSION=$( <$VERSION_FILE_DESTINATION )
  fi

  curl -o $VERSION_FILE_DESTINATION https://blackducksoftware.github.io/hub-detect/latest-commit-id.txt
  LATEST_VERSION=$( <$VERSION_FILE_DESTINATION )

  if [ $DETECT_USE_SNAPSHOT -eq 1 ]; then
    echo "will look for snapshot: ${DETECT_LATEST_SNAPSHOT}"
    DETECT_DESTINATION="${DETECT_JAR_PATH}/${DETECT_LATEST_SNAPSHOT}"
    DETECT_SOURCE=$DETECT_LATEST_SNAPSHOT
  else
    echo "will look for release: ${DETECT_LATEST_RELEASE}"
    DETECT_DESTINATION="${DETECT_JAR_PATH}/${DETECT_LATEST_RELEASE}"
    DETECT_SOURCE=$DETECT_LATEST_RELEASE
  fi

  USE_REMOTE=1
  if [ "$CURRENT_VERSION" != "$LATEST_VERSION" ] && [ $DETECT_USE_SNAPSHOT -eq 1 ]; then
    echo "You don't have the latest snapshot, so the new snapshot will be downloaded."
  elif [ ! -f $DETECT_DESTINATION ]; then
    echo "You don't have the current file, so it will be downloaded."
  else
    echo "You have already downloaded the latest file, so the local file will be used."
    USE_REMOTE=0
  fi

  if [ $USE_REMOTE -eq 1 ]; then
    echo "getting ${DETECT_SOURCE} from remote"
    curl -o $DETECT_DESTINATION https://blackducksoftware.github.io/hub-detect/$DETECT_SOURCE
    echo "saved ${DETECT_SOURCE} to ${DETECT_DESTINATION}"
  fi
}

run_detect() {
  JAVACMD="java -jar ${DETECT_DESTINATION}"
  echo "running detect: ${JAVACMD} ${JAVAOPTS}"
  rm $DETECT_JAR_PATH/hub-detect-java.sh
  echo "#!/bin/sh" >> $DETECT_JAR_PATH/hub-detect-java.sh
  echo "" >> $DETECT_JAR_PATH/hub-detect-java.sh
  echo $JAVACMD $JAVAOPTS >> $DETECT_JAR_PATH/hub-detect-java.sh
  source $DETECT_JAR_PATH/hub-detect-java.sh
  RESULT=$?
  echo "Result code of ${RESULT}, exiting"
  exit $RESULT
}

run