# Code location (scan) naming

By default, a code location (scan) name generated by a detector is constructed from information that it derives
from the package manager, such as project name and version, sub-project, or module if applicable,
and the detector type. Code location names generated by detectors end in `bom`.

A code location name generated by the ${blackduck_signature_scanner_name} is constructed from the source directory name,
project name, and project version. Code location names generated by the ${blackduck_signature_scanner_name} end in `scan`.

Optionally, you can add a [prefix](../../properties/configuration/project/#scan-name-prefix-advanced) to the automatically
generated code location names, or provide a base [name](../../properties/configuration/project/#scan-name-advanced).
