# Uncomment the next line to define a global platform for your project
#platform :ios, '9.0'

target 'black-duck-swift-sample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for black-duck-swift-sample
  pod 'Allihoopa-macOS', '~> 1.1'
  pod 'Mapbox-macOS-SDK', '~> 0.4'
  pod 'RepliesSDK-macOS', '~> 0.2'
end

target "swift-ios-test" do
  pod 'PodioKit', '~> 2.0' #Testing
end
