# Npm support

${solution_name} has three detectors for Npm:

* Npm Package Lock detector
* Npm Package Shrinkwrap detector
* Npm Package Json detector
* Npm Cli detector

## Npm Package Lock

The Npm Package Lock is the preferred Npm detector and runs when it finds a [package-lock.json](https://docs.npmjs.com/configuring-npm/package-lock-json.html) generated by Npm.

Npm automatically generates the package-lock.json after an "npm install" which should be run prior to scanning.

This is the most accurate way ${solution_name} supports Npm as lock file contains resolved versions and all transitives.

## Npm Shrinkwrap

The Npm Shrinkwrap detector uses the [npm-shrinkwrap.json](https://docs.npmjs.com/files/shrinkwrap.json) file.

It is the same as a package-lock.json but is supposed to publishable. ${solution_name} always chooses Shrinkwrap over Package Lock.

## Npm Cli Detector

The Npm Cli detector requires a package.json and an Npm executable.

It will execute "npm -ls json" and parse the dependencies reported by the npm cli.

It requires that the Npm command succeeds - does not write to ERR and returns exit code 0.

If your Npm command does not, you can silence the errors by adding the --silent npm argument using --detect.npm.arguments.

This detector is only invoked if the other detectors are not invoked and generating lockfiles for the other detectors should be preferred.

## Npm Package Json

The Npm Cli detector is the fallback when in Build mode. When in buildless the fall back detector is Npm Package Json.

This is the least accurate of the Npm detectors.

It requires and parses a "package.json".

It will not find transitives and will only report the wild-card version present in file.