package com.blackducksoftware.integration.hub.detect.bomtool.yarn;

import static org.junit.Assert.assertEquals;

import java.util.ArrayList;
import java.util.List;

import org.junit.Before;
import org.junit.Test;

public class YarnDependencyMapperTest {

    private List<String> lines;

    @Before
    public void setup() {
        lines = new ArrayList<>();
    }

    @Test
    public void testThatYarnLockIsParsedCorrectlyToMap() {

        lines.add("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.");
        lines.add("# yarn lockfile v1");
        lines.add("");
        lines.add("");
        lines.add("async@0.9.0:");
        lines.add("  version \"0.9.0\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/async/-/async-0.9.0.tgz#ac3613b1da9bed1b47510bb4651b8931e47146c7\"");
        lines.add("colors@1.0.3:");
        lines.add("  version \"1.0.3\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/colors/-/colors-1.0.3.tgz#0433f44d809680fdeb60ed260f1b0c262e82a40b\"");

        YarnDependencyMapper yarnDependencyMapper = new YarnDependencyMapper();
        yarnDependencyMapper.getYarnDataAsMap(lines);

        assertEquals("0.9.0", yarnDependencyMapper.getResolvedVersions().get("async@0.9.0"));
        assertEquals("1.0.3", yarnDependencyMapper.getResolvedVersions().get("colors@1.0.3"));
    }

    @Test
    public void testThatYarnLockVersionsResolveAsExpected() {

        lines.add("http-proxy@^1.8.1:");
        lines.add("  version \"1.16.2\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/http-proxy/-/http-proxy-1.16.2.tgz#06dff292952bf64dbe8471fa9df73066d4f37742\"");
        lines.add("  dependencies:");
        lines.add("    eventemitter3 \"1.x.x\"");
        lines.add("    requires-port \"1.x.x\"");
        lines.add("http-server@^0.9.0:");
        lines.add("  version \"0.9.0\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/http-server/-/http-server-0.9.0.tgz#8f1b06bdc733618d4dc42831c7ba1aff4e06001a\"");

        YarnDependencyMapper yarnDependencyMapper = new YarnDependencyMapper();
        yarnDependencyMapper.getYarnDataAsMap(lines);

        assertEquals("1.16.2", yarnDependencyMapper.getVersion("http-proxy@^1.8.1"));
        assertEquals("0.9.0", yarnDependencyMapper.getVersion("http-server@^0.9.0"));
    }

    @Test
    public void testThatMultipleDepsPerLineCanBeHandledCorrectly() {

        lines.add("debug@2, debug@2.6.9, debug@^2.2.0, debug@^2.3.3, debug@~2.6.4, debug@~2.6.6:");
        lines.add("  version \"2.6.9\"");
        lines.add("  resolved \"http://nexus/nexus3/repository/npm-all/debug/-/debug-2.6.9.tgz#5d128515df134ff327e90a4c93f4e077a536341f\"");
        lines.add("  dependencies:");
        lines.add("    ms \"2.0.0\"");

        YarnDependencyMapper yarnDependencyMapper = new YarnDependencyMapper();
        yarnDependencyMapper.getYarnDataAsMap(lines);

        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@2"));
        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@2.6.9"));
        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@^2.2.0"));
        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@^2.3.3"));
        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@~2.6.4"));
        assertEquals("2.6.9", yarnDependencyMapper.getVersion("debug@~2.6.6"));

    }

    @Test
    public void testThatDependenciesWithQuotesAreResolvedCorrectly() {

        lines.add("\"cssstyle@>= 0.2.37 < 0.3.0\":");
        lines.add("  version \"0.2.37\"");
        lines.add("  resolved \"http://nexus/nexus3/repository/npm-all/cssstyle/-/cssstyle-0.2.37.tgz#541097234cb2513c83ceed3acddc27ff27987d54\"");
        lines.add("  dependencies:");
        lines.add("    cssom \"0.3.x\"");

        YarnDependencyMapper yarnDependencyMapper = new YarnDependencyMapper();
        yarnDependencyMapper.getYarnDataAsMap(lines);

        assertEquals("0.2.37", yarnDependencyMapper.getVersion("cssstyle"));
    }

}
