package com.blackducksoftware.integration.hub.detect.bomtool.yarn;

import org.junit.Test;

import java.util.ArrayList;
import java.util.List;

import static org.junit.Assert.assertEquals;

public class YarnDependencyDataTest {

    @Test
    public void testThatYarnLockIsParsedCorrectlyToMap() {

        List<String> lines = new ArrayList<>();
        lines.add("# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.");
        lines.add("# yarn lockfile v1");
        lines.add("");
        lines.add("");
        lines.add("async@0.9.0:");
        lines.add("  version \"0.9.0\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/async/-/async-0.9.0.tgz#ac3613b1da9bed1b47510bb4651b8931e47146c7\"");
        lines.add("colors@1.0.3:");
        lines.add("  version \"1.0.3\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/colors/-/colors-1.0.3.tgz#0433f44d809680fdeb60ed260f1b0c262e82a40b\"");

        YarnDependencyData yarnData = new YarnDependencyData();
        YarnDependencyData.getYarnDataAsMap(lines);

        assertEquals("0.9.0", YarnDependencyData.getResolvedVersions().get("async@0.9.0"));
        assertEquals("1.0.3", YarnDependencyData.getResolvedVersions().get("colors@1.0.3"));
    }

    @Test
    public void testThatYarnLockVersionsResolveAsExpected() {
        List<String> lines = new ArrayList<>();
        lines.add("http-proxy@^1.8.1:");
        lines.add("  version \"1.16.2\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/http-proxy/-/http-proxy-1.16.2.tgz#06dff292952bf64dbe8471fa9df73066d4f37742\"");
        lines.add("  dependencies:");
        lines.add("    eventemitter3 \"1.x.x\"");
        lines.add("    requires-port \"1.x.x\"");
        lines.add("http-server@^0.9.0:");
        lines.add("  version \"0.9.0\"");
        lines.add("  resolved \"http://nexus.fr.murex.com/nexus3/repository/npm-all/http-server/-/http-server-0.9.0.tgz#8f1b06bdc733618d4dc42831c7ba1aff4e06001a\"");

        YarnDependencyData yarnData = new YarnDependencyData();
        YarnDependencyData.getYarnDataAsMap(lines);
        System.out.println(YarnDependencyData.getResolvedVersions());

        assertEquals("1.16.2", YarnDependencyData.getVersion("http-proxy@^1.8.1"));
        assertEquals("0.9.0", YarnDependencyData.getVersion("http-server@^0.9.0"));
    }

}
